[general]
name = "soundsphere 6key arrow2 noteskin toml-v2"
inputMode = "4key"
input = ["key1", "key2", "key3", "key4", "key5", "key6"]
unit = 480
scroll = 1

[columns]
x = 0
y = 450
align = "center"
width = [64, 64, 64, 64, 64, 64]
height = [64, 64, 64, 64, 64, 64]
space = [32, 0, 0, 0, 0, 0, 32]

[guidelines]
layer = 5
y = 0
width = [0, -2, 0, 0, 0, 2, 0]
height = [480, 480, 480, 480, 480, 480, 480]
images = ["pixel.png", "pixel.png", "pixel.png", "pixel.png", "pixel.png", "pixel.png", "pixel.png"]

[measureline]
height = 2
layer = 0
image = "pixel.png"

[bga]
color = [63, 63, 63, 255]
layer = -1

[keys]
padding = 30
width = [64, 64, 64, 64, 64, 64]
height = [64, 64, 64, 64, 64, 64]
layer = 4
pressed = ["key2/left1.png", "key2/left1.png", "key2/down1.png", "key2/up1.png", "key2/right1.png", "key2/right1.png"]
released = ["key2/left0.png", "key2/left0.png", "key2/down0.png", "key2/up0.png", "key2/right0.png", "key2/right0.png"]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = ["note2/left.png", "note2/left.png", "note2/down.png", "note2/up.png", "note2/right.png", "note2/right.png"]
[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = ["note2/left.png", "note2/left.png", "note2/down.png", "note2/up.png", "note2/right.png", "note2/right.png"]
[notes.LongNote.Body]
layer = 1
images = ["note2/body.png", "note2/body.png", "note2/body.png", "note2/body.png", "note2/body.png", "note2/body.png"]
[notes.LongNote.Tail]
layer = 2
images = ["note2/tail.png", "note2/tail.png", "note2/tail.png", "note2/tail.png", "note2/tail.png", "note2/tail.png"]
[notes.SoundNote]
[notes.SoundNote.Head]
layer = 3
images = ["note/mine.png", "note/mine.png", "note/mine.png", "note/mine.png", "note/mine.png", "note/mine.png"]

[playfield]
[playfield.score]
class = "ScoreDisplay"
field = "score"
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Semibold.ttf"
size = 40
xywh = [0, 0, 0.993, 1]
origin = "all"
layer = 5
[playfield.accuracy]
class = "ScoreDisplay"
field = "accuracy"
format = "%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 32
xywh = [0, 0.06, 0.993, 1]
origin = "all"
layer = 5
[playfield.combo]
class = "ScoreDisplay"
field = "combo"
format = "%d"
align = ["center", "center"]
color = [255, 255, 255, 95]
font = "resources/fonts/SourceCodePro-Bold.ttf"
size = 240
xywh = [0, 0, 480, 461]
origin = "lane"
layer = 5
[playfield.timegate]
class = "ScoreDisplay"
field = "timegate"
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "resources/fonts/SourceCodePro-Regular.ttf"
size = 28
xywh = [0, 0, 480, 475]
origin = "lane"
layer = 5
[playfield.accuracyGraph]
class = "PointGraph"
r = 1
lineColor = [255, 255, 255, 127]
color = [127, 127, 127, 255]
xywh = [0, 120, 480, 240]
origin = "lane"
layer = 0
counterPath = "hits.lua"
[playfield.progressBar]
class = "ProgressBar"
color = [255, 255, 255, 255]
direction = "left-right"
mode = "+"
xywh = [0, 0.995, 1, 0.005]
origin = "all"
layer = 0
[playfield.hpBar]
class = "HpBar"
color = [255, 255, 255, 255]
direction = "down-up"
mode = "+"
xywh = [0, 0, 0.005, 1]
origin = "all"
layer = 0
